var products = {
  "items":[
    {
      "desc":"test1",
      "imageUrl":"assets/images/products/1.jpg",
      "type":"新款",
      "point":"强悍",
      "name":"苹果笔记本",
    },
    {
      "desc":"test2",
      "imageUrl":"assets/images/products/2.jpg",
      "type":"新款",
      "point":"强悍",
      "name":"苹果笔记本",
    },
    {
      "desc":"test3",
      "imageUrl":"assets/images/products/3.jpg",
      "type":"新款",
      "point":"强悍",
      "name":"苹果笔记本",
    },
    {
      "desc":"test4",
      "imageUrl":"assets/images/products/4.jpg",
      "type":"新款",
      "point":"强悍",
      "name":"苹果笔记本",
    },
    {
      "desc":"test5",
      "imageUrl":"assets/images/products/1.jpg",
      "type":"新款",
      "point":"强悍",
      "name":"苹果笔记本",
    },
    {
      "desc":"test6",
      "imageUrl":"assets/images/products/2.jpg",
      "type":"新款",
      "point":"强悍",
      "name":"苹果笔记本",
    },
    {
      "desc":"test7",
      "imageUrl":"assets/images/products/1.jpg",
      "type":"新款",
      "point":"强悍",
      "name":"苹果笔记本",
    },
    {
      "desc":"test8",
      "imageUrl":"assets/images/products/1.jpg",
      "type":"新款",
      "point":"强悍",
      "name":"苹果笔记本",
    },
    {
      "desc":"test9",
      "imageUrl":"assets/images/products/1.jpg",
      "type":"新款",
      "point":"强悍",
      "name":"苹果笔记本",
    },
    {
      "desc":"test10",
      "imageUrl":"assets/images/products/1.jpg",
      "type":"新款",
      "point":"强悍",
      "name":"苹果笔记本",
    },
  ]
};

var news = {
  "item":[
    {
      "author":"张三",
      "title":"新闻1",
      "content":"新闻内容1"
    },
    {
      "author":"张三",
      "title":"新闻2",
      "content":"新闻内容1"
    },
    {
      "author":"张三",
      "title":"新闻3",
      "content":"新闻内容1"
    },
    {
      "author":"张三",
      "title":"新闻4",
      "content":"新闻内容1"
    },
    {
      "author":"张三",
      "title":"新闻5",
      "content":"新闻内容1"
    },
    {
      "author":"张三",
      "title":"新闻6",
      "content":"新闻内容1"
    },
  ]
};